[project]
name = "silverways-svi"
version = "0.1.0"
description = "Run deep learning models on Street View Imagery and save predictions."
requires-python = ">=3.11,<3.12"

[project.scripts]
silverways = "silverways_svi.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["silverways_svi*"]