# Input file of the road network
roads_file: "${storage.sds}/osm/roads.gpkg"
colum_id: "osm_id"

# Lis of indicators
features:
  slope:
    enabled: true
    dem_file: "${storage.cache}/mannheim_dem.tif"
    out_file: "${storage.cache}/roads_with_slope.gpkg"
    max_slope_threshold: 6   # percent; above this = barrier

  canopy_coverage:
    enabled: false
    raster_file: "${storage.sds}/chm.tif"
    out_file: "${storage.cache}/canopy_coverage.gpkg"
    threshold: 2.0 # height of a minimal tree
    buffer: 3 # meters

  greeness_svi:
    enabled: false
    directory: "${storage.sds}/google-predictions"
    out_file: "${storage.cache}/greeness_svi.gpkg"

  sky_svi:
    enabled: false
    directory: "${storage.sds}/google-predictions"
    out_file: "${storage.cache}/sky-svi.gpkg"

  accessibility:
    enabled: false
    input_file: "${storage.sds}/osm/osm_anemities.gpkg"
    out_file: "${storage.cache}/heat_stress.gpkg"
    max_distance: 1000
    buffer: 100

  safety:
    enabled: false
    input_file: "${storage.sds}/osm/street_lighting.gpkg"
    raster_file: "${storage.sds}/nighttime_light.tif"
    out_file: "${storage.cache}/safety.gpkg"
    buffer: 20

  benches:
    enabled: false
    benches_file: "${storage.sds}/osm/benches.gpkg"
    search_radius: 50
    buffer: 20
    out_file: "${storage.cache}/benches.gpkg"

  services:
    enabled: false
    pois_file: "${storage.sds}/osm/pois.gpkg"
    categories: ["pharmacy", "doctors", "shop", "cafe"]
    max_distance: 1000  # meters; services within 1 km are relevant
    buffer: 150
    out_file: "${storage.cache}/services.gpkg"





